[package]
name = "async-rs"
version = "0.6.1"
edition = "2024"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "Async runtime abstration"
repository = "https://github.com/amqp-rs/async-rs"
readme = "README.md"
documentation = "https://docs.rs/async-rs"
keywords = ["async", "await", "futures", "executor"]
categories = ["asynchronous", "concurrency"]
license = "BSD-2-Clause"
rust-version = "1.85.0"

[features]
default = ["tokio"]
async-global-executor = ["dep:async-global-executor"]
async-io = ["dep:async-io", "async-global-executor?/async-io"]
hickory-dns = ["dep:hickory-resolver", "tokio"] # hickory-dns only supports tokio as of now
smol = ["dep:smol", "async-io"] # async-io required for implementing IoSafe
tokio = ["dep:tokio", "dep:tokio-stream", "async-global-executor?/tokio", "hickory-resolver?/tokio"]

[dependencies]
async-trait = "^0.1.89"
cfg-if = "^1.0"
futures-core = "^0.3"
futures-io = "^0.3"

[dependencies.async-global-executor]
version = "^3.1"
optional = true
default-features = false

[dependencies.async-io]
version = "^2.0"
optional = true

[dependencies.hickory-resolver]
version = "^0.25"
optional = true
default-features = false
features = ["system-config"]

[dependencies.smol]
version = "^2.0"
optional = true

[dependencies.tokio]
version = "^1.47"
optional = true
default-features = false
features = ["net", "rt", "rt-multi-thread", "time"]

[dependencies.tokio-stream]
version = "^0.1"
optional = true

[dependencies.tokio-util]
version = "^0.7"
default-features = false
features = ["compat"]

[dev-dependencies.tokio]
version = "^1.47"
features = ["macros", "rt-multi-thread"]

[[example]]
name = "tokio"
required-features = ["tokio"]

[[example]]
name = "send-recv"
required-features = ["tokio"]

[package.metadata.docs.rs]
all-features = true

[badges]
maintenance = { status = "actively-developed" }
